const menus = {
    loginMenu: "Login",
    signupMenu: "Signup",
    changeData: "Change data",
    changeEmail: "Change email",
    emailConfirmation: "Email confirmation",
    changePassword: "Change password",
    forgotPasswordMenu: "Forgot password",
    deleteAccount: "Delete account",
    logoutMenu: "Logout",
    homeMenu: "Home",
    gettingStartedMenu: "Getting started",
    apiReferenceMenu: "Api reference",
    gitHubMenu: "GitHub",
    newPostMenu: "New post",
    editMenu: "Edit",
    deleteMenu: "Delete",
    banMenu: "Ban",
    approveMenu: "Approve",
    featuredMenu: "Mark featured",
    removeFeaturedMenu: "Remove featured",
    accountSettingsMenu: "Account settings",
    userPostsMenu: "User posts",
    myPostsMenu: "My posts",
    dashboardMenu: "Dashboard",
    userProfileMenu: "User profile",
    deletedPostsMenu: "Deleted posts",
};

export default menus;
