const titles = {
    loginTitle: "Login",
    accountTitle: "Account settings",
    changeDataTitle: "Change data",
    changeEmailTitle: "Change email",
    emailConfirmationTitle: "Email confirmation",
    signupTitle: "Signup",
    logoutTitle: "Logout",
    forgotPasswordTitle: "Forgot password",
    resetPasswordTitle: "Reset password",
    changePasswordTitle: "Change password",
    deleteAccountTitle: "Delete account",
    homeTitle: "Home",
    postTitle: "Post",
    newPostTitle: "New post",
    editPostTitle: "Edit post",
    statusBannedTitle: "Banned",
    statusDeletedTitle: "Deleted",
    statusMissingDataTitle: "Missing data",
    statusApprovedTitle: "Approved",
    statusFeaturedTitle: "Featured",
    statusCreatedTitle: "Created",
    dialogDeletePostTitle: "Delete post",
    dialogBanPostTitle: "Ban post",
    dialogApprovePostTitle: "Approve post",
    dialogMarkFeaturedPostTitle: "Mark post to featured",
    dialogRemoveMarkFeaturedPostTitle: "Remove featured mark of post",
    dialogDeleteAccountTitle: "Delete account",

    userTitle: "User",
    editUserTitle: "Edit user",
    dashboardTitle: "Dashboard",
};

export default titles;
