const titles = {
    loginTitle: "Login",
    accountTitle: "Account settings",
    changeDataTitle: "Change data",
    changeEmailTitle: "Change email",
    emailConfirmationTitle: "Email confirmation",
    signupTitle: "Signup",
    logoutTitle: "Logout",
    forgotPasswordTitle: "Forgot password",
    resetPasswordTitle: "Reset password",
    changePasswordTitle: "Change password",
    deleteAccountTitle: "Delete account",
    homeTitle: "Home",
    postTitle: "Post",
    newPostTitle: "New post",
    editPostTitle: "Edit post",
    statusBannedTitle: "Banned",
    statusDeletedTitle: "Deleted",
    statusAuthorDeletedTitle: "Author deleted",
    statusMissingDataTitle: "Missing data",
    statusApprovedTitle: "Approved",
    statusFeaturedTitle: "Featured",
    statusCreatedTitle: "Created",
    dialogDeleteEntryTitle: "Delete post",
    dialogBanEntryTitle: "Ban post",
    dialogApproveEntryTitle: "Approve post",
    dialogMarkFeaturedEntryTitle: "Mark post to featured",
    dialogRemoveMarkFeaturedEntryTitle: "Remove featured mark of post",
    dialogDeleteAccountTitle: "Delete account",

    userTitle: "User",
    userProfileTitle: "User profile",
    editUserTitle: "Edit user",
    dashboardTitle: "Dashboard",
    userPostsTitle: "User posts",
    userDeletedPostsTitle: "Deleted posts",
    myPostsTitle: "My posts",
    myDeletedPostsTitle: "My deleted posts"
};

export default titles;
